[package]
name = "macroquad_android"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "=0.4.13"

[package.metadata.android]
package_name = "dev.spectorstudios.macroquad_android"
label = "Macro Test"

[package.metadata.android.activity_attributes]
"android:exported" = "true"
