name: Rust

on: ['push']

env:
  CARGO_TERM_COLOR: always

jobs:
  android:
    name: Android APK Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Find NDK
        run: ls -l ${ANDROID_HOME}/ndk/27.2.12479018
          

#      - uses: nttld/setup-ndk@v1
#        id: setup-ndk
#        with:
#         ndk-version: r25b
#         add-to-path: true
#         local-cache: true
#         link-to-sdk: true

      - name: Install cargo-quad-apk
        uses: baptiste0928/cargo-install@v3.3.0
        with:
          crate: cargo-quad-apk
          git: https://github.com/not-fl3/cargo-quad-apk
        #run: cargo install --git "https://github.com/not-fl3/cargo-quad-apk.git"

      - name: Downgrade macroquad
        run: |
          cargo remove macroquad
          cargo add macroquad@0.4.13

      - name: Native build
        run: cargo build
        
      - name: cargo quad-apk
        env:
          NDK_HOME: ${ANDROID_HOME}/ndk/27.2.12479018
        run: |
          echo $NDK_HOME
          cargo quad-apk build --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: target/android-artifacts/release/apk/
