name: Rust

on: ['push']

env:
  CARGO_TERM_COLOR: always

jobs:
  android:
    name: Android APK Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update
        run: |
          rustup update
          cargo --version

      - name: Downgrade macroquad
        run: |
          cargo remove macroquad
          cargo add macroquad@0.4.13

      - name: Native build
        run: cargo build
        
      - name: cargo quad-apk
        run: cargo quad-apk build --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: target/android-artifacts/release/apk/
