name: Rust

on: ['push']

env:
  CARGO_TERM_COLOR: always

jobs:
  android:
    name: Android APK Build
    runs-on: ubuntu-latest
    container: notfl3/cargo-apk
    steps:
      - uses: actions/checkout@v2

#      - name: Rust target install
#        run: |
#          rustup target add armv7-linux-androideabi
#          rustup target add aarch64-linux-android
#          rustup target add i686-linux-android
#          rustup target add x86_64-linux-android

#      - uses: nttld/setup-ndk@v1
#        id: setup-ndk
#        with:
#         ndk-version: r25b
#         add-to-path: true
#         local-cache: true
#         link-to-sdk: true

#      - name: Install cargo-quad-apk
#        uses: baptiste0928/cargo-install@v3.3.0
#        with:
#          crate: cargo-quad-apk
#          git: https://github.com/not-fl3/cargo-quad-apk
        #run: cargo install --git "https://github.com/not-fl3/cargo-quad-apk.git"

      - name: Reinstall Rust
        run: |
          rustup self uninstall
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup target add armv7-linux-androideabi
          rustup target add aarch64-linux-android
          rustup target add i686-linux-android
          rustup target add x86_64-linux-android
          cargo install --git https://github.com/not-fl3/cargo-quad-apk.git
        
      - name: Downgrade macroquad
        run: |
          cargo remove macroquad
          cargo add macroquad@0.4.13

      - name: Native build
        run: cargo build
        
      - name: cargo quad-apk
        run: |
          echo $NDK_HOME
          ls -l $NDK_HOME
          cargo quad-apk build --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: target/android-artifacts/release/apk/
