name: Rust

on: ['push']

env:
  CARGO_TERM_COLOR: always

jobs:
  android:
    name: Android APK Build
    runs-on: ubuntu-latest
    container: notfl3/cargo-apk
    steps:
      - uses: actions/checkout@v2

      - name: Re-add macroquad
        run: |
          cargo remove macroquad
          cargo add macroquad
        
      - name: cargo quad-apk
        run: cargo quad-apk build --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: target/android-artifacts/release/apk/
