name: Rust

on: ['push']

env:
  CARGO_TERM_COLOR: always

jobs:
  android:
    name: Android APK Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update
        run: |
          rustup update
          cargo --version

      - name: Install
        run: cargo install cargo-quad-apk

      - name: Version check
        run: |
          cargo --version
          rustc --version

      - name: Native build
        run: cargo build
        
      - name: cargo quad-apk
        run: cargo quad-apk build --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: target/android-artifacts/release/apk/
